---
rule-providers:
  Rule Direct:
    type: file
    behavior: classical
    path: "./rule_provider/Direct.yaml"
  Rule Reject:
    type: file
    behavior: classical
    path: "./rule_provider/Reject.yaml"
  Rule Games:
    type: file
    behavior: classical
    path: "./rule_provider/Games.yaml"
proxy-providers:
  Proxy Private:
    type: file
    path: "./proxy_provider/Private.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Proxy Public:
    type: file
    path: "./proxy_provider/Public.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: Private
  type: url-test
  disable-udp: false
  use:
  - Proxy Private
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: Public
  type: url-test
  disable-udp: false
  use:
  - Proxy Public
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: Games
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - Private
  - Public
  use:
  - Proxy Private
  - Proxy Public
  url: http://www.gstatic.com/generate_204
  interval: '300'
dns:
  nameserver:
  - 192.168.8.1
  - dhcp://"eth1"
  - dhcp://"eth2"
  - dhcp://"usb0"
  - dhcp://"wwan0"
  - https://dns-google.com/dns-query
  - tls://dns-google.com/
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
  - "+.*"
  default-nameserver:
  - 192.168.8.1
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
secret: cybercloud
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
ipv6: false
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
profile:
  store-selected: true
  store-fake-ip: true
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,Rule Direct,DIRECT
- RULE-SET,Rule Reject,REJECT
- RULE-SET,Rule Games,Games
- MATCH,GLOBAL